// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDACKH_oYvakvGk0p0U5XB2IQTGgf3Y8-E',
    appId: '1:625133380:android:5b2c0dc714983dc91bb911',
    messagingSenderId: '625133380',
    projectId: 'gully-team',
    storageBucket: 'gully-team.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDACKH_oYvakvGk0p0U5XB2IQTGgf3Y8-E',
    appId: '1:625133380:android:5b2c0dc714983dc91bb911',
    messagingSenderId: '625133380',
    projectId: 'gully-team',
    storageBucket: 'gully-team.appspot.com',
    androidClientId: '625133380-l8f5kh9vrgtc4gbkvkjsq0eic0mucqjo.apps.googleusercontent.com',
    iosClientId: '625133380-lovspuomoojkkroghl6pni8957jl0sc8.apps.googleusercontent.com',
    iosBundleId: 'com.nileegames.gullyApp',
  );

}